config/routes.rb
Rails.application.routes.draw do
  resources :clicks
  resources :stats
  root 'stats#index'
  get '/__.gif', to: 'clicks#create'
end

app/models/click.rb
class Click < ActiveRecord::Base
  belongs_to :stat
end

app/models/stat.rb
class Stat < ActiveRecord::Base
  has_many :clicks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clicks_controller.rb
class ClicksController < ApplicationController
  before_action :set_click, only: [:show, :edit, :update, :destroy]

  # GET /clicks
  # GET /clicks.json
  def index
    @clicks = Click.all
  end

  # GET /clicks/1
  # GET /clicks/1.json
  def show
  end

  # GET /clicks/new
  def new
    @click = Click.new
  end

  # GET /clicks/1/edit
  def edit
  end

  # POST /clicks
  # POST /clicks.json
  def create
    @click = Click.new(click_params)

    respond_to do |format|
      if @click.save
        format.html { redirect_to @click, notice: 'Click was successfully created.' }
        format.json { render :show, status: :created, location: @click }
      else
        format.html { render :new }
        format.json { render json: @click.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clicks/1
  # PATCH/PUT /clicks/1.json
  def update
    respond_to do |format|
      if @click.update(click_params)
        format.html { redirect_to @click, notice: 'Click was successfully updated.' }
        format.json { render :show, status: :ok, location: @click }
      else
        format.html { render :edit }
        format.json { render json: @click.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clicks/1
  # DELETE /clicks/1.json
  def destroy
    @click.destroy
    respond_to do |format|
      format.html { redirect_to clicks_url, notice: 'Click was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_click
      @click = Click.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def click_params
      params.permit(:referrer, :ip)
    end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  before_action :set_stat, only: [:show, :edit, :update, :destroy]

  # GET /stats
  # GET /stats.json
  def index
    @stats = Stat.all
  end

  # GET /stats/1
  # GET /stats/1.json
  def show
  end

  # GET /stats/new
  def new
    @stat = Stat.new
  end

  # GET /stats/1/edit
  def edit
  end

  # POST /stats
  # POST /stats.json
  def create
    @stat = Stat.new(stat_params)

    respond_to do |format|
      if @stat.save
        format.html { redirect_to @stat, notice: 'Stat was successfully created.' }
        format.json { render :show, status: :created, location: @stat }
      else
        format.html { render :new }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stats/1
  # PATCH/PUT /stats/1.json
  def update
    respond_to do |format|
      if @stat.update(stat_params)
        format.html { redirect_to @stat, notice: 'Stat was successfully updated.' }
        format.json { render :show, status: :ok, location: @stat }
      else
        format.html { render :edit }
        format.json { render json: @stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stats/1
  # DELETE /stats/1.json
  def destroy
    @stat.destroy
    respond_to do |format|
      format.html { redirect_to stats_url, notice: 'Stat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stat
      @stat = Stat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stat_params
      params.require(:stat).permit(:domain)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clicks_helper.rb
module ClicksHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/clicks/_form.html.erb
<%= form_for(@click) do |f| %>
  <% if @click.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@click.errors.count, "error") %> prohibited this click from being saved:</h2>

      <ul>
      <% @click.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stat_id %><br>
    <%= f.text_field :stat_id %>
  </div>
  <div class="field">
    <%= f.label :referer %><br>
    <%= f.text_field :referer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clicks/edit.html.erb
<h1>Editing click</h1>

<%= render 'form' %>

<%= link_to 'Show', @click %> |
<%= link_to 'Back', clicks_path %>

app/views/clicks/index.html.erb
<h1>Listing clicks</h1>

<table>
  <thead>
    <tr>
      <th>Stat</th>
      <th>Referer</th>
      <th >ip</th>
    </tr>
  </thead>

  <tbody>
    <% @clicks.each do |click| %>
      <tr>
        <td><%= click.stat %></td>
        <td><%= click.referrer %></td>
        <td><%= click.ip %></td>
        <td><%= click.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Click', new_click_path %>

app/views/clicks/new.html.erb
<h1>New click</h1>

<%= render 'form' %>

<%= link_to 'Back', clicks_path %>

app/views/clicks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stat:</strong>
  <%= @click.stat %>
</p>

<p>
  <strong>Referer:</strong>
  <%= @click.referer %>
</p>

<%= link_to 'Edit', edit_click_path(@click) %> |
<%= link_to 'Back', clicks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/stats/_form.html.erb
<%= form_for(@stat) do |f| %>
  <% if @stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stat.errors.count, "error") %> prohibited this stat from being saved:</h2>

      <ul>
      <% @stat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :domain %><br>
    <%= f.text_field :domain %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stats/edit.html.erb
<h1>Editing stat</h1>

<%= render 'form' %>

<%= link_to 'Show', @stat %> |
<%= link_to 'Back', stats_path %>

app/views/stats/index.html.erb
<h1>Listing stats</h1>

<table>
  <thead>
    <tr>
      <th>Domain</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stats.each do |stat| %>
      <tr>
        <td><%= stat.domain %></td>
        <td><%= link_to 'Show', stat %></td>
        <td><%= link_to 'Edit', edit_stat_path(stat) %></td>
        <td><%= link_to 'Destroy', stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stat', new_stat_path %>

app/views/stats/new.html.erb
<h1>New stat</h1>

<%= render 'form' %>

<%= link_to 'Back', stats_path %>

app/views/stats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Domain:</strong>
  <%= @stat.domain %>
</p>

<%= link_to 'Edit', edit_stat_path(@stat) %> |
<%= link_to 'Back', stats_path %>